name: CDN Cache Refresh and Pre-warm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  refresh-cdn:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install alibabacloud_cdn20180510

    - name: Refresh CDN Cache (Clear)
      env:
        ALIBABA_CLOUD_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      run: python .github/scripts/cdn_refresh.py -r .github/scripts/urllist.txt -t clear

    - name: Pre-warm CDN Cache (Push)
      env:
        ALIBABA_CLOUD_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      run: python .github/scripts/cdn_refresh.py -r .github/scripts/urllist.txt -t push